### ISSUE TITLE
lets annotate services with their external URLs (e.g. for linking web applications in browsers)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/exposecontroller#1]
there's background of where this issue comes from here:
https://github.com/fabric8io/fabric8/issues/6290

essentially we've lots of complex code in both the fabric8 console and back end java code trying to figure this out; it would be much simpler to just annotate automatically services with their external URLs :)

**Comment by rawlingsj** [comment]
This is done now.  Most of the work was added with this commit https://github.com/fabric8io/exposecontroller/commit/b1d7324184167fa53dc80175bf58c01c61bed735
