### ISSUE TITLE
Change how the default route domain is detected on OpenShift

### ISSUE THREAD

**Issue by bbrowning** [fabric8io/exposecontroller#35]
The code `exposestrategy/route.go` attempts to lookup the default domain via `getAutoDefaultDomain` if one isn't explicitly given and use that to create a hostname for the generated route on OpenShift. This requires cluster-wide admin privileges to do.

Instead of doing this, I propose we pass a blank hostname when creating the RouteSpec if no explicit domain is given and OpenShift will automatically generate one for us that includes the default domain. We can then retrieve the hostname from the generated route for use with `addServiceAnnotation`. The end result will be the same but this latter method does not require cluster-wide admin privileges.

**Comment by jstrachan** [comment]
good call - updated to use that mechanism so it uses the `spec.host` value that gets put onto Routes
