### ISSUE TITLE
have a startup mode of 'auto'?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/exposecontroller#5]
to make a single YAML that can startup fabric8 on kubernetes, the main 2 parts of parameterization required are `domain` if folks use ingress/router and `expose-rule`.

I wonder if we could default expose-rule to `auto` which would then reuse the same logic in gofabric8 to default the mode? (e.g. try detect mini* and use nodePort etc otherwise if it spots a router / ingress-controller use that otherwise default to load-balancer).

Am just pondering how we can make fabric8 as easy to install as possible on vanilla kubernetes

**Comment by rawlingsj** [comment]
Yeah; so move the code that figures out the `expose-rule` into the exposecontroller and run when its starts? That way everything is self contained.

**Comment by jstrachan** [comment]
yeah! figure then we can default the config to 'auto' which then uses that rule to figure out what the rule is - or folks can explicitly set the rule (to opt out of the best guess discovery logic)

**Comment by ffang** [comment]
Hi @rawlingsj ,

Seems this change now break the vagrant for fabric8-installer/openshift.
After use "vagrant up" the exposecontroller pod never get started
```
oc get pods
NAME                              READY     STATUS             RESTARTS   AGE
docker-registry-1-apowg           1/1       Running            0          2h
exposecontroller-1-t6w0v          0/1       CrashLoopBackOff   35         2h
fabric8-anlpc                     1/1       Running            0          2h
fabric8-docker-registry-1-ozuvc   1/1       Running            0          2h
fabric8-forge-1-077aj             1/1       Running            0          2h
gogs-1-4tge3                      1/1       Running            0          2h
jenkins-1-8lvec                   1/1       Running            0          2h
nexus-1-g5ohj                     1/1       Running            0          2h
router-1-7sxt8                    2/2       Running            0          2h
```
And from the exposecontroller pods log I can see
oc logs exposecontroller-1-t6w0v
```

I1012 10:28:56.907075       1 round_trippers.go:303] Request Headers:
I1012 10:28:56.907079       1 round_trippers.go:306]     Accept: application/json, */*
I1012 10:28:56.907082       1 round_trippers.go:306]     User-Agent: exposecontroller/v1.3.0+$Format:%h$ (linux/amd64) kubernetes/$Format
I1012 10:28:56.907085       1 round_trippers.go:306]     Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImV4cG9zZWNvbnRyb2xsZXItdG9rZW4tcW8yMWciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZXhwb3NlY29udHJvbGxlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjY2OWVmZWFmLTkwNTAtMTFlNi05MzAwLTA4MDAyN2I1YzJmNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmV4cG9zZWNvbnRyb2xsZXIifQ.D42_xBczmMJ9ExBR3j6dL-hvFV1xSVWGYlYBBG5n09FBmNDjUUWKbrT1BR0sERIXedF3xME9FAeNIWmIUeWx7-6EPHnaIrDp92oShbxkmr400WxfPZzLatyJeK13JK9f_DjDdYQKB5vxyUI0UvCk6eo2y9UwR9kV98XBazIgSxZ30vM6Iq-diQY8ftc-gHMho0fbNS2ecxkIOw25PHzm2rzXd_wcOvd4b0x3tBZt-W-_LFawkTDCEwyITJpvharBzlMbSMiqBL_VXJEmL9xRqmFLhnP37-4YeBSAwTHrGTZm_epJqwLD4T5zNXBIp5H6dZr-4geKQpl14ydOCxkYOg
I1012 10:28:56.909347       1 round_trippers.go:321] Response Status: 404 Not Found in 2 milliseconds
I1012 10:28:56.909374       1 round_trippers.go:324] Response Headers:
I1012 10:28:56.909378       1 round_trippers.go:327]     Cache-Control: no-store
I1012 10:28:56.909380       1 round_trippers.go:327]     Content-Type: application/json
I1012 10:28:56.909382       1 round_trippers.go:327]     Date: Wed, 12 Oct 2016 10:28:56 GMT
I1012 10:28:56.909385       1 round_trippers.go:327]     Content-Length: 192
I1012 10:28:56.909429       1 request.go:901] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"spc-balancer\" not found","reason":"NotFound","details":{"name":"spc-balancer","kind":"pods"},"code":404}
F1012 10:28:56.909602       1 exposecontroller.go:66] failed to create new strategy: failed to create auto expose strategy: failed to get a domain: no known automatic ways to get an external ip to use with xip
```
So seems the new introduced spc-balancer  is the culprit here.

Btw, I can run vagrant for fabric8-installer/openshift successfully yesterday.  Could you please take a look? Is there any easy way I can still use the older version exposecontroller?

Thanks
Freeman

**Comment by rawlingsj** [comment]
Ok thanks @ffang you should be able to just update the deploymentconfig to use the old version in the image for things to work as yesterday until I fix

The previous image tag to use is 2.2.267
```
oc edit dc exposecontroller 
```

and update the `image: `

**Comment by rawlingsj** [comment]
@ffang  I can see the problem and you should be able to update the exposecontroller config map and still use the latest version.

https://github.com/fabric8io/exposecontroller/#types

The issue here is we currently try to figure out the defaults.  You could try to update the configmap to use the following replacing 192.1.2.3 with the IP of the VM
```
exposer: Route
domain: 192.1.2.3.xip.io
```

FWIW we're going to update the fabric8-installer/openshift project as deprecated in favour of using [minishift](https://github.com/jimmidyson/minishift) which works so much better all round.

**Comment by ffang** [comment]
@rawlingsj  thanks for the hint.
But with the 
```
exposer: Route
domain: 192.1.2.3.xip.io
```

the exposecontroller pod get started, but I can't open the fabirc8 console anymore
with
```
gofabric8 service fabric8
```
I get 
```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"http://fabric8.default.172.28.128.4.xip.io/"}
```
in my brower and no way to let me input admin/admin username/password like before.

Also with
```
oc edit dc exposecontroller 
```
to try to use previous working version 2.2.267 still doesn't work, after the edition I delete the exposecontroller pod but still run into the spc-balancer issue, do I need change more? Could you elaborate how I can update the image to use the 2.2.267 version?
Thanks!
Freeman

**Comment by rawlingsj** [comment]
@ffang yeah thats where you need to replace 192.1.2.3 with the IP of the vagrant VM
I've not used vagrant in a while but does `vagrant ip` give you an IP address?  If so replace 192.1.2.3 with it in the exposecontroller configmap.

restart the exposecontroller pod and you should be good to go

**Comment by ffang** [comment]
@rawlingsj yeah I was using the vagrant VM ip address 172.28.128.4 but it doesn't work for me.

**Comment by rawlingsj** [comment]
@ffang ok I'll take a proper look at it and report back on this this issue https://github.com/fabric8io/exposecontroller/issues/13

FWIW I really recommend not using that vagrant image and switching to https://github.com/jimmidyson/minishift

**Comment by rawlingsj** [comment]
@ffang not sure if you've seen but the issue you had has been resolved.  I've just tested after pulling the latest https://github.com/fabric8io/fabric8-installer/tree/master/vagrant/openshift which includes an updated gofabric8 version and the exposecontroller pod starts + I can log into the fabric8 console fine.

**Comment by ffang** [comment]
Thanks @rawlingsj !
I will try it. Btw, I already tried the minishift way and it works perfectly.
